language: go

go_import_path: code.gitea.io/gitea

go:
  - 1.6
  - 1.7

env:
  TAGS: cert sqlite pam miniwinsvc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libpam-dev

script:
  - make clean
  - make vet

  # - make lint

  - make test
  - make build

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: never
    urls:
      - https://webhooks.gitter.im/e/ee6b822f3cf54c98e70c
      - https://webhooks.gitter.im/e/87428658ef177ce8a7e4
      - https://webhooks.gitter.im/e/a1d2b69804dfda72187e
